import type { Metadata } from "next";

import { SessionProvider } from "next-auth/react";

import { auth } from "@/auth";

import "@/styles/globals.css";

import { cn } from "@/lib/utils";

import { geistSans } from "@/common/lib/fonts";

import { LayoutsPropsType } from "@/common/types/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<LayoutsPropsType>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={cn("font-geist", geistSans.variable)}>{children}</body>
      </html>
    </SessionProvider>
  );
}
